# coding=utf-8
"""
生成 Edgi / DeepCraft 模型对应的 RT-AK 模型 C 文件草图。

当前生成物通过 backend_edgi_* 间接调用 DeepCraft / Imagimob IMAI runtime。

目标调用链：

rt_ai_<model>_model_init
-> backend_edgi_init
-> IMAI_init

rt_ai_<model>_model_run
-> backend_edgi_run
-> IMAI_compute

rt_ai_<model>_model_deinit
-> backend_edgi_deinit
-> IMAI_finalize
"""

from pathlib import Path


def _to_symbol_name(model_name: str) -> str:
    return model_name.strip().lower().replace("-", "_").replace(" ", "_")


def generate_rt_ai_model_c(model_name: str, output_dir: str, metadata: dict) -> Path:
    symbol = _to_symbol_name(model_name)
    macro = symbol.upper()

    out_dir = Path(output_dir) / symbol
    out_dir.mkdir(parents=True, exist_ok=True)

    source_path = out_dir / f"rt_ai_{symbol}_model.c"

    content = f"""/*
 * Auto-generated by RT-AK Plugin Edgi.
 *
 * Current stage:
 * - minimal RT-AK model wrapper
 * - call backend_edgi_* instead of direct IMAI_* APIs
 * - UVC / LCD / postprocess are intentionally excluded
 */

#include "rt_ai_{symbol}_model.h"
#include "backend_edgi.h"

#include <stdint.h>

static backend_edgi_config_t g_rt_ai_{symbol}_backend_config = {{
    RT_AI_{macro}_MODEL_NAME,
    RT_AI_{macro}_INPUT_SIZE,
    RT_AI_{macro}_OUTPUT_SIZE,
    0,
}};

int rt_ai_{symbol}_model_init(void)
{{
    return backend_edgi_init(&g_rt_ai_{symbol}_backend_config);
}}

int rt_ai_{symbol}_model_run(void)
{{
    return backend_edgi_run(0, 0);
}}

int rt_ai_{symbol}_model_deinit(void)
{{
    return backend_edgi_deinit();
}}

void *rt_ai_{symbol}_model_get_input(uint32_t index)
{{
    return backend_edgi_get_input(index);
}}

void *rt_ai_{symbol}_model_get_output(uint32_t index)
{{
    return backend_edgi_get_output(index);
}}
"""

    source_path.write_text(content, encoding="utf-8")
    return source_path