# coding=utf-8
"""
生成 Edgi / DeepCraft 模型对应的 RT-AK 模型 C 文件草图。

当前生成物不是最终 backend，只是把 IMAI_init / IMAI_compute /
IMAI_finalize 包装成可检查的模型 wrapper。
"""

from pathlib import Path


def _to_symbol_name(model_name: str) -> str:
    return model_name.strip().lower().replace("-", "_").replace(" ", "_")


def generate_rt_ai_model_c(model_name: str, output_dir: str, metadata: dict) -> Path:
    symbol = _to_symbol_name(model_name)

    out_dir = Path(output_dir) / symbol
    out_dir.mkdir(parents=True, exist_ok=True)

    source_path = out_dir / f"rt_ai_{symbol}_model.c"

    input_size = metadata.get("input_size", 320 * 320 * 3)
    output_size = metadata.get("output_size", 40)

    content = f"""/*
 * Auto-generated by RT-AK Plugin Edgi.
 *
 * Current stage:
 * - minimal DeepCraft / Imagimob wrapper
 * - not yet final rt_ai_core registration
 * - UVC / LCD / postprocess are intentionally excluded
 */

#include "rt_ai_{symbol}_model.h"

#include <stdint.h>
#include <string.h>

/*
 * model.h is generated by DeepCraft / Imagimob.
 * The final BSP integration must ensure this header is in include path.
 */
#include "model.h"

static uint8_t g_rt_ai_{symbol}_input[RT_AI_{symbol.upper()}_INPUT_SIZE];
static float g_rt_ai_{symbol}_output[RT_AI_{symbol.upper()}_OUTPUT_SIZE];

int rt_ai_{symbol}_model_init(void)
{{
    memset(g_rt_ai_{symbol}_input, 0, sizeof(g_rt_ai_{symbol}_input));
    memset(g_rt_ai_{symbol}_output, 0, sizeof(g_rt_ai_{symbol}_output));

    return IMAI_init();
}}

int rt_ai_{symbol}_model_run(void)
{{
    return IMAI_compute(g_rt_ai_{symbol}_input, g_rt_ai_{symbol}_output);
}}

int rt_ai_{symbol}_model_deinit(void)
{{
    IMAI_finalize();
    return 0;
}}

void *rt_ai_{symbol}_model_get_input(uint32_t index)
{{
    if (index != 0U)
    {{
        return 0;
    }}

    return g_rt_ai_{symbol}_input;
}}

void *rt_ai_{symbol}_model_get_output(uint32_t index)
{{
    if (index != 0U)
    {{
        return 0;
    }}

    return g_rt_ai_{symbol}_output;
}}
"""

    source_path.write_text(content, encoding="utf-8")
    return source_path