# coding=utf-8
"""
Generate RT-AK standard model registration C file for Edgi / DeepCraft.

This generator intentionally does NOT generate old wrapper APIs such as:

    rt_ai_<model>_model_init()
    rt_ai_<model>_model_run()
    rt_ai_<model>_model_get_input()
    rt_ai_<model>_model_get_output()

Target RT-AK call chain:

    INIT_APP_EXPORT(rt_ai_<model>_model_register)
        -> rt_ai_register()
            -> backend_edgi()
                -> ai->init       = _edgi_backend_init
                -> ai->get_input  = _edgi_backend_get_input
                -> ai->run        = _edgi_backend_run
                -> ai->get_output = _edgi_backend_get_output

Application side:

    rt_ai_find("<model>")
        -> rt_ai_init()
        -> rt_ai_input()
        -> rt_ai_run()
        -> rt_ai_output()
"""

from pathlib import Path
from typing import Dict, Any


def _to_symbol_name(model_name: str) -> str:
    """
    Convert model name to valid C symbol fragment.

    Example:
        object_detect -> object_detect
        object-detect -> object_detect
        object detect -> object_detect
    """
    return model_name.strip().lower().replace("-", "_").replace(" ", "_")


def _to_macro_name(model_name: str) -> str:
    """
    Convert model name to valid C macro fragment.

    Example:
        object_detect -> OBJECT_DETECT
    """
    return _to_symbol_name(model_name).upper()


def generate_rt_ai_model_c(model_name: str, output_dir: str, metadata: Dict[str, Any]) -> Path:
    """
    Generate rt_ai_<model>_model.c.

    Args:
        model_name:
            Logical model name, for example "object_detect".

        output_dir:
            Base generated directory. The final file will be placed at:
                <output_dir>/<symbol>/rt_ai_<symbol>_model.c

        metadata:
            Reserved for future use. Current implementation relies on
            macros generated in rt_ai_<model>_model.h.

    Returns:
        Path to generated C source file.
    """
    del metadata

    symbol = _to_symbol_name(model_name)
    macro = _to_macro_name(model_name)

    out_dir = Path(output_dir) / symbol
    out_dir.mkdir(parents=True, exist_ok=True)

    source_path = out_dir / f"rt_ai_{symbol}_model.c"

    content = f"""/*
 * Auto-generated by RT-AK Plugin Edgi.
 *
 * Model: {model_name}
 *
 * This file registers the Edgi / DeepCraft model into RT-AK core.
 *
 * UVC / LCD / postprocess logic is intentionally excluded.
 */

#include <rtthread.h>

#include "rt_ai.h"
#include "rt_ai_common.h"
#include "backend_edgi.h"
#include "model.h"
#include "rt_ai_{symbol}_model.h"

#ifdef RT_AI_USE_EDGI

#if defined(__STDC_VERSION__) && (__STDC_VERSION__ >= 201112L)
#define RT_AI_{macro}_STATIC_ASSERT(_expr, _msg) _Static_assert((_expr), _msg)
#else
#define RT_AI_{macro}_STATIC_ASSERT_GLUE2(_a, _b) _a##_b
#define RT_AI_{macro}_STATIC_ASSERT_GLUE(_a, _b) \\
    RT_AI_{macro}_STATIC_ASSERT_GLUE2(_a, _b)
#define RT_AI_{macro}_STATIC_ASSERT(_expr, _msg) \\
    typedef char RT_AI_{macro}_STATIC_ASSERT_GLUE( \\
        rt_ai_{symbol}_static_assert_, __LINE__)[(_expr) ? 1 : -1]
#endif

RT_AI_{macro}_STATIC_ASSERT(
    RT_AI_{macro}_IN_1_SIZE == IMAI_DATAIN_COUNT,
    "RT-AK Edgi input count mismatch");
RT_AI_{macro}_STATIC_ASSERT(
    RT_AI_{macro}_IN_1_SIZE_BYTES == (IMAI_DATAIN_COUNT * sizeof(IMAI_DATAIN_TYPE)),
    "RT-AK Edgi input byte size mismatch");
RT_AI_{macro}_STATIC_ASSERT(
    RT_AI_{macro}_OUT_1_SIZE == IMAI_DATAOUT_COUNT,
    "RT-AK Edgi output count mismatch");
RT_AI_{macro}_STATIC_ASSERT(
    RT_AI_{macro}_OUT_1_SIZE_BYTES == (IMAI_DATAOUT_COUNT * sizeof(IMAI_DATAOUT_TYPE)),
    "RT-AK Edgi output byte size mismatch");

#define RT_AI_{macro}_INFO                       \\
{{                                               \\
    RT_AI_{macro}_IN_NUM,                        \\
    RT_AI_{macro}_OUT_NUM,                       \\
    {{ RT_AI_{macro}_IN_1_SIZE_BYTES }},         \\
    {{ RT_AI_{macro}_OUT_1_SIZE_BYTES }},        \\
    RT_AI_{macro}_WORK_BUFFER_BYTES,             \\
    0,                                           \\
}}

#define RT_AI_{macro}_HANDLE                     \\
{{                                               \\
    .info = RT_AI_{macro}_INFO,                  \\
}}

#define RT_EDGI_AI_{macro}                       \\
{{                                               \\
    .parent = RT_AI_{macro}_HANDLE,              \\
    .config =                                    \\
    {{                                           \\
        RT_AI_{macro}_MODEL_NAME,                \\
        RT_AI_{macro}_IN_1_SIZE_BYTES,           \\
        RT_AI_{macro}_OUT_1_SIZE,                \\
        RT_NULL,                                 \\
    }},                                          \\
}}

static edgi_ai_t rt_edgi_ai_{symbol} = RT_EDGI_AI_{macro};

static int rt_ai_{symbol}_model_register(void)
{{
    rt_err_t ret;

    ret = rt_ai_register(RT_AI_T(&rt_edgi_ai_{symbol}),
                         RT_AI_{macro}_MODEL_NAME,
                         0,
                         backend_edgi,
                         &rt_edgi_ai_{symbol});

    if (ret != RT_AI_OK)
    {{
        rt_kprintf("[RT-AK][Edgi] register model %s failed: %d\\r\\n",
                   RT_AI_{macro}_MODEL_NAME,
                   ret);
        return ret;
    }}

    rt_kprintf("[RT-AK][Edgi] register model %s success\\r\\n",
               RT_AI_{macro}_MODEL_NAME);

    return RT_AI_OK;
}}
INIT_APP_EXPORT(rt_ai_{symbol}_model_register);

#endif /* RT_AI_USE_EDGI */
"""

    source_path.write_text(content, encoding="utf-8")
    return source_path
