# coding=utf-8
"""
生成 Edgi / DeepCraft 模型对应的 RT-AK 模型头文件草图。

当前阶段只输出到 generated/<model_name>/，不修改 BSP。
"""

from pathlib import Path


def _to_symbol_name(model_name: str) -> str:
    return model_name.strip().lower().replace("-", "_").replace(" ", "_")


def _to_macro_name(model_name: str) -> str:
    return _to_symbol_name(model_name).upper()


def generate_rt_ai_model_h(model_name: str, output_dir: str, metadata: dict) -> Path:
    symbol = _to_symbol_name(model_name)
    macro = _to_macro_name(model_name)

    out_dir = Path(output_dir) / symbol
    out_dir.mkdir(parents=True, exist_ok=True)

    header_path = out_dir / f"rt_ai_{symbol}_model.h"

    input_size = metadata.get("input_size", 320 * 320 * 3)
    output_size = metadata.get("output_size", 40)
    input_shape = metadata.get("input_shape", [3, 320, 320])
    output_shape = metadata.get("output_shape", [40])

    content = f"""#ifndef __RT_AI_{macro}_MODEL_H__
#define __RT_AI_{macro}_MODEL_H__

/*
 * Auto-generated by RT-AK Plugin Edgi.
 *
 * Current stage:
 * - minimal model wrapper skeleton
 * - not yet final RT-AK backend integration
 * - not coupled with UVC / LCD demo
 */

#include <stdint.h>

#ifdef __cplusplus
extern "C" {{
#endif

#define RT_AI_{macro}_MODEL_NAME          "{model_name}"
#define RT_AI_{macro}_INPUT_SIZE          ({input_size}U)
#define RT_AI_{macro}_OUTPUT_SIZE         ({output_size}U)
#define RT_AI_{macro}_INPUT_DTYPE         "uint8"
#define RT_AI_{macro}_OUTPUT_DTYPE        "float32"

#define RT_AI_{macro}_INPUT_SHAPE_TEXT    "{input_shape}"
#define RT_AI_{macro}_OUTPUT_SHAPE_TEXT   "{output_shape}"

int rt_ai_{symbol}_model_init(void);
int rt_ai_{symbol}_model_run(void);
int rt_ai_{symbol}_model_deinit(void);

void *rt_ai_{symbol}_model_get_input(uint32_t index);
void *rt_ai_{symbol}_model_get_output(uint32_t index);

#ifdef __cplusplus
}}
#endif

#endif /* __RT_AI_{macro}_MODEL_H__ */
"""

    header_path.write_text(content, encoding="utf-8")
    return header_path