# coding=utf-8
"""
Generate RT-AK model header for Edgi / DeepCraft.

This header only describes model metadata.
It intentionally does NOT declare old wrapper APIs such as:

    rt_ai_<model>_model_init()
    rt_ai_<model>_model_run()
    rt_ai_<model>_model_get_input()
    rt_ai_<model>_model_get_output()

Application code should use standard RT-AK APIs:

    rt_ai_find()
    rt_ai_init()
    rt_ai_input()
    rt_ai_run()
    rt_ai_output()
"""

from pathlib import Path


def _to_symbol_name(model_name: str) -> str:
    return model_name.strip().lower().replace("-", "_").replace(" ", "_")


def _to_macro_name(model_name: str) -> str:
    return _to_symbol_name(model_name).upper()


def _shape_to_text(shape) -> str:
    if isinstance(shape, (list, tuple)):
        return "[" + ", ".join(str(x) for x in shape) + "]"
    return str(shape)


def generate_rt_ai_model_h(model_name: str, output_dir: str, metadata: dict) -> Path:
    symbol = _to_symbol_name(model_name)
    macro = _to_macro_name(model_name)

    out_dir = Path(output_dir) / symbol
    out_dir.mkdir(parents=True, exist_ok=True)

    header_path = out_dir / f"rt_ai_{symbol}_model.h"

    input_size = metadata.get("input_size", 320 * 320 * 3)
    output_size = metadata.get("output_size", 40)
    input_shape = _shape_to_text(metadata.get("input_shape", [3, 320, 320]))
    output_shape = _shape_to_text(metadata.get("output_shape", [40]))

    content = f"""#ifndef __RT_AI_{macro}_MODEL_H__
#define __RT_AI_{macro}_MODEL_H__

/*
 * Auto-generated by RT-AK Plugin Edgi.
 *
 * Model: {model_name}
 *
 * This file only contains RT-AK model metadata.
 * UVC / LCD / postprocess logic is intentionally excluded.
 */

#include <stdint.h>

#ifdef __cplusplus
extern "C" {{
#endif

#define RT_AI_{macro}_MODEL_NAME              "{model_name}"

#define RT_AI_{macro}_IN_NUM                  (1)
#define RT_AI_{macro}_OUT_NUM                 (1)

#define RT_AI_{macro}_IN_1_SIZE               ({input_size}U)
#define RT_AI_{macro}_IN_1_SIZE_BYTES         (RT_AI_{macro}_IN_1_SIZE * sizeof(uint8_t))

#define RT_AI_{macro}_OUT_1_SIZE              ({output_size}U)
#define RT_AI_{macro}_OUT_1_SIZE_BYTES        (RT_AI_{macro}_OUT_1_SIZE * sizeof(float))

#define RT_AI_{macro}_WORK_BUFFER_BYTES       (0U)
#define RT_AI_{macro}_BUFFER_ALIGNMENT        (16U)

/*
 * Legacy aliases kept for existing generated demo config users.
 * Application code should prefer rt_ai_edgi_active_model.h.
 */
#define RT_AI_{macro}_INPUT_SIZE              RT_AI_{macro}_IN_1_SIZE
#define RT_AI_{macro}_OUTPUT_SIZE             RT_AI_{macro}_OUT_1_SIZE

#define RT_AI_{macro}_INPUT_DTYPE             "uint8"
#define RT_AI_{macro}_OUTPUT_DTYPE            "float32"
#define RT_AI_{macro}_INPUT_SHAPE_TEXT        "{input_shape}"
#define RT_AI_{macro}_OUTPUT_SHAPE_TEXT       "{output_shape}"

#ifdef __cplusplus
}}
#endif

#endif /* __RT_AI_{macro}_MODEL_H__ */
"""

    header_path.write_text(content, encoding="utf-8")
    return header_path
