# coding=utf-8

import argparse
import sys

from .config import DEFAULT_MODEL_NAME, DEFAULT_RUNTIME
from .plugin_edgi_parser import platform_parameters
from .prepare_work import (
    check_bsp_project,
    check_deepcraft_dir,
    print_dry_run_report,
)
from .generate_model_files import parse_model_metadata
from .generate_rt_ai_model_h import generate_rt_ai_model_h
from .gen_rt_ai_model_c import generate_rt_ai_model_c
from .export_to_project import export_to_project
from .generate_demo_config import generate_demo_config

def build_parser():
    parser = argparse.ArgumentParser(
        description="RT-AK Edgi Talk plugin tool"
    )

    parser.add_argument(
        "--project",
        type=str,
        required=True,
        help="RT-Thread BSP 工程路径",
    )

    parser.add_argument(
        "--model",
        type=str,
        default="",
        help="模型路径。第一版 Edgi 插件暂不直接使用该参数，保留用于兼容 RT-AK 基础参数",
    )

    parser.add_argument(
        "--model_name",
        type=str,
        default=DEFAULT_MODEL_NAME,
        help="注册到 RT-AK 的模型名称",
    )

    parser.add_argument(
        "--platform",
        type=str,
        default="edgi",
        help="RT-AK 平台名称，第一版固定为 edgi",
    )

    parser.add_argument(
        "--clear",
        action="store_true",
        help="保留 RT-AK 通用参数。第一版不执行清理动作",
    )

    parser = platform_parameters(parser)
    return parser


def _check_before_generate(opt):
    """生成前统一做 dry-run 级别检查。"""
    bsp_ok, bsp_errors = check_bsp_project(opt.project)
    model_ok, model_errors = check_deepcraft_dir(opt.deepcraft_dir)

    if not bsp_ok:
        print("BSP check failed:")
        for err in bsp_errors:
            print(f"  - {err}")

    if not model_ok:
        print("Model check failed:")
        for err in model_errors:
            print(f"  - {err}")

    return bsp_ok and model_ok


def generate_model_wrapper(opt):
    """生成 Edgi RT-AK 模型 wrapper 草图。"""
    if not _check_before_generate(opt):
        print("生成失败：dry-run 检查未通过。")
        return 1

    metadata = parse_model_metadata(opt.deepcraft_dir)

    h_path = generate_rt_ai_model_h(
        model_name=opt.model_name,
        output_dir=opt.output_dir,
        metadata=metadata,
    )

    c_path = generate_rt_ai_model_c(
        model_name=opt.model_name,
        output_dir=opt.output_dir,
        metadata=metadata,
    )
    cfg_path = generate_demo_config(
        model_name=opt.model_name,
        output_dir=opt.output_dir,
        metadata=metadata,
    )

    print("=" * 70)
    print("Edgi RT-AK model skeleton generated by plugin_edgi.py")
    print("=" * 70)
    print(f"model_name  : {opt.model_name}")
    print(f"model_h     : {metadata['model_h']}")
    print(f"input_shape : {metadata['input_shape']}")
    print(f"output_shape: {metadata['output_shape']}")
    print(f"input_size  : {metadata['input_size']}")
    print(f"output_size : {metadata['output_size']}")
    print("-" * 70)
    print(f"generated h : {h_path}")
    print(f"generated c : {c_path}")
    print("=" * 70)
    print(f"generated cfg: {cfg_path}")
    
    return 0


def export_generated_files(opt):
    """导出插件产物到 BSP applications/rt_ai_edgi。"""
    try:
        target_dir = export_to_project(
            project=opt.project,
            output_dir=opt.output_dir,
            export_dir=opt.export_dir,
        )
    except Exception as exc:
        print(f"导出失败：{exc}")
        return 1

    print("=" * 70)
    print("Edgi RT-AK files exported")
    print("=" * 70)
    print(f"target_dir : {target_dir}")
    print("exported   : backend_plugin_edgi/")
    print("exported   : generated/")
    print("exported   : SConscript")
    print("exported : Kconfig")
    print("-" * 70)
    print("注意：已导出 applications/rt_ai_edgi/Kconfig。")
    print("注意：仍需在 BSP 根 Kconfig 中手动添加：")
    print('source "$BSP_DIR/applications/rt_ai_edgi/Kconfig"')
    print("注意：当前阶段未修改 BSP 根目录 SConscript / rtconfig.h / Kconfig。")
    print("=" * 70)

    return 0


def main(argv=None):
    parser = build_parser()
    opt = parser.parse_args(argv)

    if opt.platform != "edgi":
        print(f"错误：当前插件只支持 --platform edgi，当前输入为: {opt.platform}")
        return 1

    if not opt.runtime:
        opt.runtime = DEFAULT_RUNTIME

    ret = 0

    if opt.dry_run:
        ret = print_dry_run_report(opt)
        if ret != 0:
            return ret

    if opt.generate:
        ret = generate_model_wrapper(opt)
        if ret != 0:
            return ret

    if opt.export:
        if not opt.generate:
            print("错误：当前阶段 --export 需要和 --generate 一起使用。")
            return 1

        ret = export_generated_files(opt)
        if ret != 0:
            return ret

    if not opt.dry_run and not opt.generate and not opt.export:
        print("当前阶段请指定 --dry_run、--generate 或 --generate --export。")
        return 1

    return ret

class Plugin:
    def __init__(self, opt):
        self.opt = opt

    def run_plugin(self):
        opt = self.opt

        if getattr(opt, "platform", None) != "edgi":
            print(f"错误：当前插件只支持 --platform edgi，当前输入为: {getattr(opt, 'platform', None)}")
            return 1

        if not getattr(opt, "runtime", None):
            opt.runtime = DEFAULT_RUNTIME

        ret = 0

        if getattr(opt, "dry_run", False):
            ret = print_dry_run_report(opt)
            if ret != 0:
                return ret

        if getattr(opt, "generate", False):
            ret = generate_model_wrapper(opt)
            if ret != 0:
                return ret

        if getattr(opt, "export", False):
            if not getattr(opt, "generate", False):
                print("错误：当前阶段 --export 需要和 --generate 一起使用。")
                return 1

            ret = export_generated_files(opt)
            if ret != 0:
                return ret

        if (
            not getattr(opt, "dry_run", False)
            and not getattr(opt, "generate", False)
            and not getattr(opt, "export", False)
        ):
            print("当前阶段请指定 --dry_run、--generate 或 --generate --export。")
            return 1

        return ret

if __name__ == "__main__":
    sys.exit(main())