# coding=utf-8
"""
RT-AK Edgi Talk 平台插件入口。

当前支持：
- --dry_run：只检查 BSP 和 DeepCraft / Imagimob 模型产物；
- --generate：检查通过后生成 rt_ai_<model>_model.c/h 草图。

当前不做：
- 不修改原始 BSP 工程；
- 不复制 UVC / LCD demo；
- 不注入 SConscript；
- 不修改 rtconfig.h。
"""

import argparse
import sys

from config import DEFAULT_MODEL_NAME, DEFAULT_RUNTIME
from plugin_edgi_parser import platform_parameters
from prepare_work import (
    check_bsp_project,
    check_deepcraft_dir,
    print_dry_run_report,
)
from generate_model_files import parse_model_metadata
from generate_rt_ai_model_h import generate_rt_ai_model_h
from gen_rt_ai_model_c import generate_rt_ai_model_c


def build_parser():
    parser = argparse.ArgumentParser(
        description="RT-AK Edgi Talk plugin tool"
    )

    parser.add_argument(
        "--project",
        type=str,
        required=True,
        help="RT-Thread BSP 工程路径",
    )

    parser.add_argument(
        "--model",
        type=str,
        default="",
        help="模型路径。第一版 Edgi 插件暂不直接使用该参数，保留用于兼容 RT-AK 基础参数",
    )

    parser.add_argument(
        "--model_name",
        type=str,
        default=DEFAULT_MODEL_NAME,
        help="注册到 RT-AK 的模型名称",
    )

    parser.add_argument(
        "--platform",
        type=str,
        default="edgi",
        help="RT-AK 平台名称，第一版固定为 edgi",
    )

    parser.add_argument(
        "--clear",
        action="store_true",
        help="保留 RT-AK 通用参数。第一版不执行清理动作",
    )

    parser = platform_parameters(parser)
    return parser


def _check_before_generate(opt):
    """生成前统一做 dry-run 级别检查。"""
    bsp_ok, bsp_errors = check_bsp_project(opt.project)
    model_ok, model_errors = check_deepcraft_dir(opt.deepcraft_dir)

    if not bsp_ok:
        print("BSP check failed:")
        for err in bsp_errors:
            print(f"  - {err}")

    if not model_ok:
        print("Model check failed:")
        for err in model_errors:
            print(f"  - {err}")

    return bsp_ok and model_ok


def generate_model_wrapper(opt):
    """生成 Edgi RT-AK 模型 wrapper 草图。"""
    if not _check_before_generate(opt):
        print("生成失败：dry-run 检查未通过。")
        return 1

    metadata = parse_model_metadata(opt.deepcraft_dir)

    h_path = generate_rt_ai_model_h(
        model_name=opt.model_name,
        output_dir=opt.output_dir,
        metadata=metadata,
    )

    c_path = generate_rt_ai_model_c(
        model_name=opt.model_name,
        output_dir=opt.output_dir,
        metadata=metadata,
    )

    print("=" * 70)
    print("Edgi RT-AK model skeleton generated by plugin_edgi.py")
    print("=" * 70)
    print(f"model_name  : {opt.model_name}")
    print(f"model_h     : {metadata['model_h']}")
    print(f"input_shape : {metadata['input_shape']}")
    print(f"output_shape: {metadata['output_shape']}")
    print(f"input_size  : {metadata['input_size']}")
    print(f"output_size : {metadata['output_size']}")
    print("-" * 70)
    print(f"generated h : {h_path}")
    print(f"generated c : {c_path}")
    print("=" * 70)

    return 0


def main(argv=None):
    parser = build_parser()
    opt = parser.parse_args(argv)

    if opt.platform != "edgi":
        print(f"错误：当前插件只支持 --platform edgi，当前输入为: {opt.platform}")
        return 1

    if not opt.runtime:
        opt.runtime = DEFAULT_RUNTIME

    if opt.dry_run:
        dry_ret = print_dry_run_report(opt)
        if not opt.generate:
            return dry_ret

    if opt.generate:
        return generate_model_wrapper(opt)

    print("当前阶段请指定 --dry_run 或 --generate。")
    return 1


if __name__ == "__main__":
    sys.exit(main())