/*
 * RT-AK Plugin Edgi minimal backend implementation.
 *
 * This backend only wraps:
 * - IMAI_init
 * - IMAI_compute
 * - IMAI_finalize
 *
 * It intentionally excludes:
 * - UVC camera capture
 * - YUYV to RGB888 preprocessing
 * - model-specific postprocess
 * - LCD overlay
 * - MSH command logic
 * - worker thread scheduling
 */

#include "backend_edgi.h"

#include <stdint.h>
#include <string.h>

#include "cy_device.h"
/*
 * model.h is generated by DeepCraft / Imagimob.
 * The final BSP integration must ensure this header is in include path.
 */
#include "model.h"

#if defined(__GNUC__)
#define BACKEND_EDGI_ALIGN(n) __attribute__((aligned(n)))
#define BACKEND_EDGI_SECTION(name) __attribute__((section(name)))
#else
#define BACKEND_EDGI_ALIGN(n)
#define BACKEND_EDGI_SECTION(name)
#endif

#define BACKEND_EDGI_INPUT_SECTION       BACKEND_EDGI_SECTION(".cy_ml_arena_data")
#define BACKEND_EDGI_OUTPUT_SECTION      BACKEND_EDGI_SECTION(".cy_ml_postproc_data")
#define BACKEND_EDGI_MODEL_HEADER_WORD0  (0x00000024UL)
#define BACKEND_EDGI_MODEL_HEADER_WORD1  (0x334c4654UL)
#define BACKEND_EDGI_CACHE_OUTER_LAYERS  (2U)

static BACKEND_EDGI_INPUT_SECTION BACKEND_EDGI_ALIGN(16)
uint8_t g_backend_edgi_input[BACKEND_EDGI_INPUT_SIZE];

static BACKEND_EDGI_OUTPUT_SECTION BACKEND_EDGI_ALIGN(16)
float g_backend_edgi_output[BACKEND_EDGI_OUTPUT_SIZE];

static int g_backend_edgi_initialized = 0;
static int g_backend_edgi_last_error = BACKEND_EDGI_OK;
static uint8_t g_backend_edgi_restore_unalign_trp;
static uint32_t g_backend_edgi_saved_ccr;

static backend_edgi_config_t g_backend_edgi_config = {
    "object_detect",
    BACKEND_EDGI_INPUT_SIZE,
    BACKEND_EDGI_OUTPUT_SIZE,
    0,
};

extern uint8_t __cy_ml_model_data_start__[];
extern uint8_t __cy_ml_model_data_end__[];
extern const uint8_t __cy_ml_model_data_load_start__[];
extern const uint8_t __cy_ml_model_data_load_end__[];
extern void mtb_ml_set_cache_mgmt_type(uint32_t type);

static void backend_edgi_sync_model_blob_from_flash(void)
{
    uint8_t *runtime = __cy_ml_model_data_start__;
    const uint8_t *flash = __cy_ml_model_data_load_start__;
    uintptr_t runtime_start = (uintptr_t)__cy_ml_model_data_start__;
    uintptr_t runtime_end = (uintptr_t)__cy_ml_model_data_end__;
    uintptr_t flash_start = (uintptr_t)__cy_ml_model_data_load_start__;
    uintptr_t flash_end = (uintptr_t)__cy_ml_model_data_load_end__;
    uint32_t runtime_word0;
    uint32_t runtime_word1;
    uint32_t flash_word0;
    uint32_t flash_word1;
    int blob_same;
    size_t bytes;

    if ((runtime_end <= runtime_start) || (flash_end <= flash_start))
    {
        return;
    }

    bytes = (size_t)(runtime_end - runtime_start);
    if (bytes < (2U * sizeof(uint32_t)))
    {
        return;
    }

    if (runtime_start == flash_start)
    {
        return;
    }

    memcpy(&runtime_word0, runtime, sizeof(runtime_word0));
    memcpy(&runtime_word1, runtime + sizeof(uint32_t), sizeof(runtime_word1));
    memcpy(&flash_word0, flash, sizeof(flash_word0));
    memcpy(&flash_word1, flash + sizeof(uint32_t), sizeof(flash_word1));
    blob_same = (memcmp(runtime, flash, bytes) == 0);

    if (!blob_same ||
        (runtime_word0 != flash_word0) || (runtime_word1 != flash_word1) ||
        (runtime_word0 != BACKEND_EDGI_MODEL_HEADER_WORD0) ||
        (runtime_word1 != BACKEND_EDGI_MODEL_HEADER_WORD1))
    {
        memcpy(runtime, flash, bytes);
        rt_kprintf("[RT-AK][Edgi] blob sync flash->runtime=1 r=0x%08lx f=0x%08lx\r\n",
                   (unsigned long)runtime_start, (unsigned long)flash_start);
    }
    else
    {
        rt_kprintf("[RT-AK][Edgi] blob sync flash->runtime=0 r=0x%08lx f=0x%08lx\r\n",
                   (unsigned long)runtime_start, (unsigned long)flash_start);
    }
}

static void backend_edgi_disable_unalign_trp_if_needed(void)
{
    if ((SCB->CCR & SCB_CCR_UNALIGN_TRP_Msk) != 0U)
    {
        g_backend_edgi_saved_ccr = SCB->CCR;
        SCB->CCR = g_backend_edgi_saved_ccr & (~SCB_CCR_UNALIGN_TRP_Msk);
        __DSB();
        __ISB();
        g_backend_edgi_restore_unalign_trp = 1U;
        rt_kprintf("[RT-AK][Edgi] UNALIGN_TRP disabled for TFLM parser compatibility\r\n");
    }
    else
    {
        g_backend_edgi_restore_unalign_trp = 0U;
    }
}

static void backend_edgi_restore_unalign_trp_if_needed(void)
{
    if (g_backend_edgi_restore_unalign_trp)
    {
        SCB->CCR = g_backend_edgi_saved_ccr;
        __DSB();
        __ISB();
        g_backend_edgi_restore_unalign_trp = 0U;
    }
}

int backend_edgi_init(const backend_edgi_config_t *config)
{
    int ret;

    if (g_backend_edgi_initialized)
    {
        return BACKEND_EDGI_OK;
    }

    if (config != 0)
    {
        g_backend_edgi_config = *config;
    }

    memset(g_backend_edgi_input, 0, sizeof(g_backend_edgi_input));
    memset(g_backend_edgi_output, 0, sizeof(g_backend_edgi_output));

    backend_edgi_sync_model_blob_from_flash();
    backend_edgi_disable_unalign_trp_if_needed();

    ret = IMAI_init();
#ifdef IMAI_RET_SUCCESS
    if (ret != IMAI_RET_SUCCESS)
#else
    if (ret != 0)
#endif
    {
        g_backend_edgi_initialized = 0;
        g_backend_edgi_last_error = ret;
        backend_edgi_restore_unalign_trp_if_needed();
        return ret;
    }

    mtb_ml_set_cache_mgmt_type(BACKEND_EDGI_CACHE_OUTER_LAYERS);

    g_backend_edgi_initialized = 1;
    g_backend_edgi_last_error = BACKEND_EDGI_OK;

    return BACKEND_EDGI_OK;
}

int backend_edgi_run(const void *input, void *output)
{
    const uint8_t *runtime_input;
    float *runtime_output;
    

    if (!g_backend_edgi_initialized)
    {
        g_backend_edgi_last_error = BACKEND_EDGI_ERROR_NOT_INIT;
        return BACKEND_EDGI_ERROR_NOT_INIT;
    }

    runtime_input = (const uint8_t *)input;
    runtime_output = (float *)output;

    if (runtime_input == 0)
    {
        runtime_input = g_backend_edgi_input;
    }

    if (runtime_output == 0)
    {
        runtime_output = g_backend_edgi_output;
    }

    /*
     * Current DeepCraft / Imagimob IMAI_compute returns void.
     */

    IMAI_compute(runtime_input, runtime_output);

    g_backend_edgi_last_error = BACKEND_EDGI_OK;
    return BACKEND_EDGI_OK;
}

int backend_edgi_deinit(void)
{
    if (!g_backend_edgi_initialized)
    {
        return BACKEND_EDGI_OK;
    }

    IMAI_finalize();
    backend_edgi_restore_unalign_trp_if_needed();

    g_backend_edgi_initialized = 0;
    g_backend_edgi_last_error = BACKEND_EDGI_OK;

    return BACKEND_EDGI_OK;
}

void *backend_edgi_get_input(uint32_t index)
{
    if (index != 0U)
    {
        g_backend_edgi_last_error = BACKEND_EDGI_ERROR_BAD_INDEX;
        return 0;
    }

    return g_backend_edgi_input;
}

void *backend_edgi_get_output(uint32_t index)
{
    if (index != 0U)
    {
        g_backend_edgi_last_error = BACKEND_EDGI_ERROR_BAD_INDEX;
        return 0;
    }

    return g_backend_edgi_output;
}

int backend_edgi_is_initialized(void)
{
    return g_backend_edgi_initialized;
}

int backend_edgi_get_last_error(void)
{
    return g_backend_edgi_last_error;
}

#ifdef RT_AI_USE_EDGI

static int _edgi_backend_init(rt_ai_t ai, rt_ai_buffer_t *buf)
{
    int ret;

    RT_UNUSED(buf);

    if (ai == RT_AI_NULL)
    {
        return -RT_AI_ERROR;
    }

    ret = backend_edgi_init(&EDGI_AI_T(ai)->config);
    if (ret != BACKEND_EDGI_OK)
    {
        return -RT_AI_ERROR;
    }

    ai->input[0] = (rt_ai_buffer_t *)backend_edgi_get_input(0);
    ai->output[0] = (rt_ai_buffer_t *)backend_edgi_get_output(0);

    if (ai->input[0] == RT_AI_NULL || ai->output[0] == RT_AI_NULL)
    {
        return -RT_AI_ERROR;
    }

    return RT_AI_OK;
}

static int _edgi_backend_get_input(rt_ai_t ai, rt_ai_uint32_t index)
{
    if (ai == RT_AI_NULL || index >= ai->info.input_n)
    {
        return -RT_AI_ERROR;
    }

    ai->input[index] = (rt_ai_buffer_t *)backend_edgi_get_input(index);

    return ai->input[index] ? RT_AI_OK : -RT_AI_ERROR;
}

static int _edgi_backend_run(rt_ai_t ai, void (*callback)(void *arg), void *arg)
{
    int ret;

    if (ai == RT_AI_NULL)
    {
        return -RT_AI_ERROR;
    }

    if (ai->input[0] == RT_AI_NULL)
    {
        ai->input[0] = (rt_ai_buffer_t *)backend_edgi_get_input(0);
    }

    if (ai->output[0] == RT_AI_NULL)
    {
        ai->output[0] = (rt_ai_buffer_t *)backend_edgi_get_output(0);
    }

    ret = backend_edgi_run(ai->input[0], ai->output[0]);
    if (ret != BACKEND_EDGI_OK)
    {
        return -RT_AI_ERROR;
    }

    if (callback)
    {
        callback(arg);
    }

    return RT_AI_OK;
}

static int _edgi_backend_get_output(rt_ai_t ai, rt_ai_uint32_t index)
{
    if (ai == RT_AI_NULL || index >= ai->info.output_n)
    {
        return -RT_AI_ERROR;
    }

    ai->output[index] = (rt_ai_buffer_t *)backend_edgi_get_output(index);

    return ai->output[index] ? RT_AI_OK : -RT_AI_ERROR;
}

static int _edgi_backend_get_info(rt_ai_t ai, rt_ai_buffer_t *buf)
{
    RT_UNUSED(ai);
    RT_UNUSED(buf);
    return RT_AI_OK;
}

static int _edgi_backend_config(rt_ai_t ai, int cmd, rt_ai_buffer_t *args)
{
    RT_UNUSED(ai);
    RT_UNUSED(args);

    switch (cmd)
    {
    case RT_AI_EDGI_CMD_DEINIT:
        return backend_edgi_deinit() == BACKEND_EDGI_OK
                   ? RT_AI_OK
                   : -RT_AI_ERROR;

    default:
        return -RT_AI_ERROR;
    }
}

int backend_edgi(void *edgi_handle)
{
    rt_ai_t ai;

    if (edgi_handle == RT_AI_NULL)
    {
        return -RT_AI_ERROR;
    }

    ai = RT_AI_T(edgi_handle);

    ai->init = _edgi_backend_init;
    ai->get_input = _edgi_backend_get_input;
    ai->run = _edgi_backend_run;
    ai->get_output = _edgi_backend_get_output;
    ai->get_info = _edgi_backend_get_info;
    ai->config = _edgi_backend_config;

    /*
     * Edgi backend uses static input/output buffers.
     * Do not let rt_ai_allocate_buffer() allocate from external work_buf.
     */
    ai->mem_flag = 0;

    return RT_AI_OK;
}

#endif /* RT_AI_USE_EDGI */
