/*
 * RT-AK Plugin Edgi minimal backend implementation.
 *
 * This backend only wraps:
 * - IMAI_init
 * - IMAI_compute
 * - IMAI_finalize
 *
 * It intentionally excludes:
 * - UVC camera capture
 * - YUYV to RGB888 preprocessing
 * - model-specific postprocess
 * - LCD overlay
 * - MSH command logic
 * - worker thread scheduling
 */

#include "backend_edgi.h"

#include <stdint.h>
#include <string.h>

/*
 * model.h is generated by DeepCraft / Imagimob.
 * The final BSP integration must ensure this header is in include path.
 */
#include "model.h"

#if defined(__GNUC__)
#define BACKEND_EDGI_ALIGN(n) __attribute__((aligned(n)))
#else
#define BACKEND_EDGI_ALIGN(n)
#endif

static uint8_t g_backend_edgi_input[BACKEND_EDGI_INPUT_SIZE] BACKEND_EDGI_ALIGN(16);
static float g_backend_edgi_output[BACKEND_EDGI_OUTPUT_SIZE] BACKEND_EDGI_ALIGN(16);

static int g_backend_edgi_initialized = 0;
static int g_backend_edgi_last_error = BACKEND_EDGI_OK;

static backend_edgi_config_t g_backend_edgi_config = {
    "object_detect",
    BACKEND_EDGI_INPUT_SIZE,
    BACKEND_EDGI_OUTPUT_SIZE,
    0,
};

int backend_edgi_init(const backend_edgi_config_t *config)
{
    int ret;

    if (config != 0)
    {
        g_backend_edgi_config = *config;
    }

    memset(g_backend_edgi_input, 0, sizeof(g_backend_edgi_input));
    memset(g_backend_edgi_output, 0, sizeof(g_backend_edgi_output));

    ret = IMAI_init();
    if (ret != 0)
    {
        g_backend_edgi_initialized = 0;
        g_backend_edgi_last_error = ret;
        return ret;
    }

    g_backend_edgi_initialized = 1;
    g_backend_edgi_last_error = BACKEND_EDGI_OK;

    return BACKEND_EDGI_OK;
}

int backend_edgi_run(const void *input, void *output)
{
    const uint8_t *runtime_input;
    float *runtime_output;
    int ret;

    if (!g_backend_edgi_initialized)
    {
        g_backend_edgi_last_error = BACKEND_EDGI_ERROR_NOT_INIT;
        return BACKEND_EDGI_ERROR_NOT_INIT;
    }

    runtime_input = (const uint8_t *)input;
    runtime_output = (float *)output;

    if (runtime_input == 0)
    {
        runtime_input = g_backend_edgi_input;
    }

    if (runtime_output == 0)
    {
        runtime_output = g_backend_edgi_output;
    }

    ret = IMAI_compute(runtime_input, runtime_output);
    if (ret != 0)
    {
        g_backend_edgi_last_error = ret;
        return ret;
    }

    g_backend_edgi_last_error = BACKEND_EDGI_OK;
    return BACKEND_EDGI_OK;
}

int backend_edgi_deinit(void)
{
    if (!g_backend_edgi_initialized)
    {
        return BACKEND_EDGI_OK;
    }

    IMAI_finalize();

    g_backend_edgi_initialized = 0;
    g_backend_edgi_last_error = BACKEND_EDGI_OK;

    return BACKEND_EDGI_OK;
}

void *backend_edgi_get_input(uint32_t index)
{
    if (index != 0U)
    {
        g_backend_edgi_last_error = BACKEND_EDGI_ERROR_BAD_INDEX;
        return 0;
    }

    return g_backend_edgi_input;
}

void *backend_edgi_get_output(uint32_t index)
{
    if (index != 0U)
    {
        g_backend_edgi_last_error = BACKEND_EDGI_ERROR_BAD_INDEX;
        return 0;
    }

    return g_backend_edgi_output;
}

int backend_edgi_is_initialized(void)
{
    return g_backend_edgi_initialized;
}

int backend_edgi_get_last_error(void)
{
    return g_backend_edgi_last_error;
}