# RT-AK Plugin Edgi backend SConscript
#
# Current stage:
# - compile backend_edgi.c
# - model.c / model.h include path will be provided by final BSP integration

from building import *

cwd = GetCurrentDir()
project_root = Dir('#').abspath.replace('\\', '/')
deepcraft_root = project_root + '/libraries/Common/deepcraft_ai'

src = [
    'backend_edgi.c',
]

CPPPATH = [
    cwd,
    deepcraft_root + '/model',
]

group = DefineGroup(
    'RT-AK-Edgi-Backend',
    src,
    depend=['RT_AI_USE_EDGI'],
    CPPPATH=CPPPATH
)

Return('group')
