# -*- coding: utf-8 -*-

from building import *

cwd = GetCurrentDir()

backend_dir = cwd + '/../../rt_ai_lib/backend_plugin_edgi'
generated_dir = cwd + '/generated/object_detect'
rt_ai_lib_dir = cwd + '/../../rt_ai_lib'
rt_ai_include_dir = rt_ai_lib_dir + '/include'
deepcraft_model_dir = cwd + '/../../libraries/Common/deepcraft_ai/model'

src = [
    generated_dir + '/rt_ai_object_detect_model.c',
]

if GetDepend(['RT_AI_EDGI_MINIMAL_DEMO']):
    src += [
        cwd + '/rt_ai_edgi_minimal_demo.c',
    ]

CPPPATH = [
    cwd,
    backend_dir,
    generated_dir,
    rt_ai_lib_dir,
    rt_ai_include_dir,
    deepcraft_model_dir,
]

group = DefineGroup(
    'RT-AK-Edgi',
    src,
    depend=['RT_AI_USE_EDGI'],
    CPPPATH=CPPPATH
)

Return('group')